# ==============================================================================
#
# THIS SOFTWARE IS PROVIDED "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES,
# INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
# A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL CLOUDFLARE BE LIABLE FOR ANY DIRECT,
# INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES  (INCLUDING, BUT NOT
# LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
# BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
# STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE
# USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
# ==============================================================================

name = "cloudflare-gateway-dynamic-pages"
workers_dev = false
compatibility_date = "2024-11-25"
main = "src/main.js"

#------------------------------------------------------------------
# Insert your account id
#------------------------------------------------------------------
account_id = "d2b46b90090c5d9e61032bd23fd3f1c5"

#------------------------------------------------------------------
# Add your worker domain, for example: identity.pleasant-sensor.com
#------------------------------------------------------------------
routes = [
	{ pattern = "blocked.0security.net", custom_domain = true }	
]

#------------------------------------------------------------------
# We will fill up the kv's id in later step
#------------------------------------------------------------------
[[kv_namespaces]] 
binding = "gw_custom_pages_kv"
id = "fb27d0e7e30649d68820712fb517b17d"

[vars]
#------------------------------------------------------------------
# This should be the route pattern domain /debug , for example: https://identity.pleasant-sensor.com/debug
#------------------------------------------------------------------
CORS_ORIGIN = "blocked.0security.net/debug"  # This should be the route pattern domain /debug (https://example.com/debug)

#------------------------------------------------------------------
# Insert your account id (use the same value for both vars)
#------------------------------------------------------------------
ACCOUNT_ID = "d2b46b90090c5d9e61032bd23fd3f1c5"
ORGANIZATION_ID = "0199ce605b6c79a78c01232579bd86ec"

#------------------------------------------------------------------
# Insert your team domain without cloudflareaccess.com. for example: zt-pleasant-sensor
#------------------------------------------------------------------
ORGANIZATION_NAME = "Zero Security Corp"


DEBUG = "true"
SETUP = "false" # Enable/disable setup page access
TARGET_GROUP = "NA" # Define the "special group" that you want to use for notification

[site]
bucket = "./build"

[observability.logs]
enabled = true

[build]
command = "npm run build"


